# -------------------------------------------------------------------------
# pnpm-workspace.yaml
# This file tells pnpm that this is a "monorepo" (a single repository containing
# multiple separate packages/apps).
# It defines where pnpm should look to find those individual projects.
# -------------------------------------------------------------------------

packages:
  # The 'apps' folder contains deployable applications (like our Next.js frontend,
  # Express API, Realtime server, and BullMQ worker).
  - 'apps/*'

  # The 'packages' folder contains shared code libraries (like UI components,
  # config schemas, and logger) that the apps will import and use.
  - 'packages/*'
allowBuilds:
  '@prisma/client': true
  '@prisma/engines': true
  esbuild: true
  msgpackr-extract: true
  prisma: true
  sharp: true
minimumReleaseAgeExclude:
  - bullmq@5.80.2
  - eslint@10.7.0
